# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4fd901e0c50b40389a508fb8dc9d87d970fca679007001073fdfe3d9913e855f95ad0eb59a2c4f8587817c676294b3d3a5808390a91495f32ce2cb0cbaff0b56

test:
  secret_key_base: 91f87d17faa9fb6cd50d1c08c98fc72e56108026103ee02aac060b8370b39c492bd9f2324cac957606c8426cb52da08a57b6b8ec930b4e7499e020ce6a37c2e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
